from django.contrib import admin
from django.urls import include, path

from . import views

urlpatterns = [
    path('',views.home),
    path('user',views.user),
    path('loqout/',views.logout1),

    path('userregistration/',views.userregistration),
    path('slogin',views.slogin),
    path('addtocart',views.addtocart),
    path('adminhome/',views.adminhome),
    path('viewuser/',views.viewusers),
    path('viewreport/', views.viewreport),
    path('viewfeedback/', views.viewfeedback),
    path('viewrating/',views.viewrating),
    path('viewrating/',views.viewrating),
    path('viewcomplaints/',views.viewcomplaints),
    path('verifyuser/', views.verifyusers),
    path('uaccepted/<id>', views.uaccepted),
    path('urejected/<id>', views.urejected),
    path('verifydstaff/', views.verifydelivery),
    path('acceptdelivery/<id>/', views.acceptdelivery),
    path('rejectdelivery/<id>/', views.rejectdelivery),
    path('usercheck/', views.usercheck),
    path('blocked/<int:id>/', views.blockdelivery),
    path('unblocked/<int:id>/', views.unblockdelivery),
    path('farmercheck/', views.verifyfarmers),
    path('blockfarmer/<id>/', views.blockfarmer),
    path('unblockfarmer/<id>/', views.unblockfarmer),
    path('staff', views.verifydeliverystaff),
    path('blockdeliverystaff/<id>/', views.blockdeliverystaff),
    path('unblockdeliverystaff/<id>/', views.unblockdeliverystaff),
    # path('sendreview/', views.sendreview),
    # path('sendusercomplaint/', views.sendusercomplaint),
    path('user_chat_with_farmer', views.usendchattofamers),
    # path('edituserprofile/<user_id>/', views.edituserprofile),
    # path('chat_with_delivery/<delivery_login_id>/', views.user_chat_with_delivery),
    path('userregister', views.userregistration),
    # path('deliveryuschat',views.delchatwithus),
    # path('deliuschat',views.usdviewwchattt),
    path('shop/register',views.register),
    path('text',views.text),
    path('sendfeed',views.send_feedback),
    path('ffeedback',views.ffeedback),

    path('viewfeed',views.view_feedback),
    path('farmerregister',views.farmerregister),
    path('profregfar',views.profregfar),
    path('managestaff',views.managestaff),
    path('chatwithus',views.chatwithus),
    path('viewsingleproduct',views.viewineprod),
    path('farmerverify',views.farmerverify),
    path('updateuserprofilee',views.updateuserprofile),
    path('manageprofile',views.manageuser),
    path('deliverystaffregister',views.deliverystaffregister),
    path('products',views.productes),
    path('manageproduct',views.manageproduct),
    path('deleteprod',views.deleteprod),
    path('viewcomplaint',views.viewcomplaint),
    path('viewchat',views.viewwchattt),
    path('viewuser',views.viewuser),
    path('viewfarmer',views.viewfarmer),
    path('viewdeliverystaff',views.viewdeliverystaff),
    path('viewproduct',views.viewproduct),
    path('viewcart',views.viewcart),
    path('viewfeedbackfar',views.view_feedbackfar),
    path('viewwassign',views.viewwassign),
    # path('assign',views.assignorder),
    path('changepassword',views.change_password),
    path('sendcomplaints',views.sendcomplaint),
    path('api/urlname',views.fluttertodjango),
    path('delicomplaint',views.dsendcomplaint),
    path('delichemi',views.stviewcomplaints),
    path('deliveryreg',views.deliverystaffregister),
    path('updateorderstatuss',views.updateorderstatus),
    path('dviewfeedbackke',views.dviewfeedback),
    path('dsendcomplaintt',views.dsendcomplaint),
    path('dchatwithfarr',views.dchatwithfar),
    path('dviewwchatt',views.dviewwchat),
    path('dchatwithuserr',views.dchatwithuser),
    path('dviewwchattus',views.dviewwuschat),
    path('viewuserssss',views.userviewed),
    path('learnn',views.learn),
    path('viewfarmer',views.viewfarmer),
    path('viewStaff',views.viewStafff),
    path('viewcartt',views.viewcartee),
    path('makeorderr',views.makeorder),
    path('payy',views.pay),
    path('vieworder',views.vieworder),
    path('viewuser',views.viewuser),
    path('viewfarmer',views.viewfarmer),    
    path('viewuser',views.viewuser),
    path('userchateddddd',views.userchated),
    path('viewuserr',views.viewuserr),
    path('pickup',views.pickupview),
    path('verifyyyyfam',views.farmerverify),
    path('assignorder',views.assignorder),
    path('assignorder',views.assignorder),
    path('pickupview',views.pickupview),
    path('deliver',views.deliver),
    # path('password',views.password),
    path('change',views.password),
    path('sendfeedbackk',views.sendfeedbackk),
    path('viewfeedbackstafff',views.viewfeedbackstaff),

    path('sendcomplaintsuser',views.sendcomplaintsuser),
    path('viewcomplaintsuserrr',views.viewcomplaintsuserrr),
]
