# Generated by Django 4.1 on 2025-08-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmertable',
            name='dob',
            field=models.CharField(max_length=100),
        ),
    ]
