# Generated by Django 4.1 on 2025-08-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_farmertable_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complainttable',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('replied', 'Replied')], default='pending', max_length=10),
        ),
    ]
